apiVersion: v1
kind: Service
metadata:
  name: flask-app-svc
spec:
  selector:
    app: {{ .Values.pythonFlaskApp.name }}
  ports:
  - name: flask-port-5000
    protocol: "TCP"
    port: {{ .Values.pythonFlaskApp.restPort }}
    targetPort: {{ .Values.pythonFlaskApp.restPort }}
  type: {{ .Values.service.type }}
