apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.mysql.name }}
  labels:
    app: {{ .Values.mysql.name }}
    app.kubernetes.io/name: {{ .Values.mysql.name }}
data:
  primary.cnf: |
    # Apply this config only on the primary.
    [mysqld]
    log-bin
  replica.cnf: |
    # Apply this config only on replicas.
    [mysqld]
    super-read-only
